persistence true
persistence_location /mosquitto/data
log_dest file /mosquitto/log/mosquitto.log

# MQTT TCP (ESP32)
listener 1883
protocol mqtt

# MQTT over WebSocket
listener 9001
protocol websockets

allow_anonymous true
